from __future__ import annotations

from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row


class DuplicateEmailError(ValueError):
    pass


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class PostgresDatabase:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url.strip()

    def connect(self):
        if not self.database_url:
            raise RuntimeError("DATABASE_URL или POSTGRES_HOST/POSTGRES_DB/POSTGRES_USER/POSTGRES_PASSWORD обязательны.")
        return psycopg.connect(self.database_url, row_factory=dict_row)

    def initialize(self) -> None:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS access_users (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email TEXT NOT NULL UNIQUE,
                        full_name TEXT NOT NULL DEFAULT '',
                        role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
                        allow_all BOOLEAN NOT NULL DEFAULT FALSE,
                        source TEXT NOT NULL DEFAULT 'manual',
                        created_at TEXT NOT NULL,
                        updated_at TEXT NOT NULL
                    )
                    """
                )
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS calendar_permissions (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        access_user_id INTEGER NOT NULL REFERENCES access_users(id) ON DELETE CASCADE,
                        calendar_email TEXT NOT NULL,
                        created_at TEXT NOT NULL,
                        UNIQUE (access_user_id, calendar_email)
                    )
                    """
                )
                cursor.execute(
                    "CREATE UNIQUE INDEX IF NOT EXISTS access_users_email_lower_idx ON access_users (LOWER(email))"
                )
                cursor.execute(
                    "CREATE INDEX IF NOT EXISTS calendar_permissions_user_idx ON calendar_permissions (access_user_id)"
                )

    def list_access_users(self) -> list[dict]:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT access_users.id, access_users.email, access_users.full_name, access_users.role,
                       access_users.allow_all, access_users.created_at, access_users.updated_at,
                       COALESCE(
                           ARRAY_AGG(calendar_permissions.calendar_email ORDER BY calendar_permissions.calendar_email)
                           FILTER (WHERE calendar_permissions.calendar_email IS NOT NULL),
                           ARRAY[]::TEXT[]
                       ) AS allowed_calendars
                FROM access_users
                LEFT JOIN calendar_permissions ON calendar_permissions.access_user_id = access_users.id
                GROUP BY access_users.id
                ORDER BY access_users.role = 'admin' DESC, LOWER(access_users.email)
                """
            ).fetchall()
        return [dict(row) for row in rows]

    def get_access_user_by_email(self, email: str) -> dict | None:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT id, email, full_name, role, allow_all, source, created_at, updated_at
                FROM access_users
                WHERE LOWER(email) = %s
                """,
                (email.strip().lower(),),
            ).fetchall()
        return dict(rows[0]) if rows else None

    def update_access_user_name(self, email: str, full_name: str) -> None:
        clean_name = full_name.strip()
        if not clean_name:
            return
        with self.connect() as connection:
            connection.execute(
                """
                UPDATE access_users
                SET full_name = %s, updated_at = %s
                WHERE LOWER(email) = %s
                """,
                (clean_name, utc_now(), email.strip().lower()),
            )

    def add_access_user(self, email: str, role: str, allow_all: bool, allowed_calendars: list[str]) -> None:
        self._validate_role(role)
        now = utc_now()
        clean_email = email.strip().lower()
        with self.connect() as connection:
            try:
                row = connection.execute(
                    """
                    INSERT INTO access_users (email, role, allow_all, source, created_at, updated_at)
                    VALUES (%s, %s, %s, 'manual', %s, %s)
                    RETURNING id
                    """,
                    (clean_email, role, allow_all, now, now),
                ).fetchone()
            except psycopg.IntegrityError as exc:
                raise DuplicateEmailError(clean_email) from exc
            self._replace_allowed_calendars(connection, int(row["id"]), allowed_calendars)

    def update_access_user(
        self, access_user_id: int, email: str, role: str, allow_all: bool, allowed_calendars: list[str]
    ) -> bool:
        self._validate_role(role)
        clean_email = email.strip().lower()
        with self.connect() as connection:
            try:
                row = connection.execute(
                    """
                    UPDATE access_users
                    SET email = %s, role = %s, allow_all = %s, updated_at = %s
                    WHERE id = %s
                    RETURNING id
                    """,
                    (clean_email, role, allow_all, utc_now(), access_user_id),
                ).fetchone()
            except psycopg.IntegrityError as exc:
                raise DuplicateEmailError(clean_email) from exc
            if not row:
                return False
            self._replace_allowed_calendars(connection, access_user_id, allowed_calendars)
        return True

    def delete_access_user(self, access_user_id: int) -> bool:
        with self.connect() as connection:
            cursor = connection.execute("DELETE FROM access_users WHERE id = %s", (access_user_id,))
        return cursor.rowcount > 0

    def user_can_access_calendar(self, user_email: str, calendar_email: str) -> bool:
        user = self.get_access_user_by_email(user_email)
        if not user:
            return False
        if user["role"] == "admin" or user["allow_all"]:
            return True
        with self.connect() as connection:
            row = connection.execute(
                """
                SELECT 1
                FROM calendar_permissions
                WHERE access_user_id = %s AND LOWER(calendar_email) = %s
                LIMIT 1
                """,
                (user["id"], calendar_email.strip().lower()),
            ).fetchone()
        return bool(row)

    def _replace_allowed_calendars(self, connection, access_user_id: int, allowed_calendars: list[str]) -> None:
        connection.execute("DELETE FROM calendar_permissions WHERE access_user_id = %s", (access_user_id,))
        now = utc_now()
        for calendar_email in dict.fromkeys(email.strip().lower() for email in allowed_calendars if email.strip()):
            connection.execute(
                """
                INSERT INTO calendar_permissions (access_user_id, calendar_email, created_at)
                VALUES (%s, %s, %s)
                ON CONFLICT (access_user_id, calendar_email) DO NOTHING
                """,
                (access_user_id, calendar_email, now),
            )

    @staticmethod
    def _validate_role(role: str) -> None:
        if role not in {"admin", "user"}:
            raise ValueError("Некорректная роль пользователя.")
